stages:
  AddData:
    cmd: zntrack run ipsuite.data_loading.add_data_ase.AddData --name AddData
    deps:
    - KCl1650K.extxyz
    params:
    - AddData
    outs:
    - nodes/AddData/atoms.h5
  test_data:
    cmd: zntrack run ipsuite.configuration_selection.uniform_energetic.UniformEnergeticSelection
      --name test_data
    deps:
    - nodes/AddData/atoms.h5
    params:
    - test_data
    outs:
    - nodes/test_data/selected_configurations.json
  train_data:
    cmd: zntrack run ipsuite.configuration_selection.random.RandomSelection --name
      train_data
    deps:
    - nodes/AddData/atoms.h5
    - nodes/test_data/selected_configurations.json
    params:
    - train_data
    outs:
    - nodes/train_data/selected_configurations.json
  validate_data:
    cmd: zntrack run ipsuite.configuration_selection.random.RandomSelection --name
      validate_data
    deps:
    - nodes/train_data/selected_configurations.json
    params:
    - validate_data
    outs:
    - nodes/validate_data/selected_configurations.json
  model_1:
    cmd: zntrack run ipsuite.models.mace_model.MACE --name model_1
    deps:
    - nodes/train_data/selected_configurations.json
    - nodes/validate_data/selected_configurations.json
    params:
    - model_1
    outs:
    - nodes/model_1/model
    - nodes/model_1/test-data.extxyz
    - nodes/model_1/train-data.extxyz
    plots:
    - nodes/model_1/training.csv:
        template: /data/fzills/tools/ipsuite/ipsuite/static_data/y_log.json
        x: epoch
        y: loss
  Prediction:
    cmd: zntrack run ipsuite.analysis.model.predict.Prediction --name Prediction
    deps:
    - nodes/model_1/model
    - nodes/model_1/test-data.extxyz
    - nodes/model_1/train-data.extxyz
    - nodes/model_1/training.csv
    - nodes/test_data/selected_configurations.json
    outs:
    - nodes/Prediction/atoms.h5
  PredictionMetrics:
    cmd: zntrack run ipsuite.analysis.model.predict.PredictionMetrics --name PredictionMetrics
    deps:
    - nodes/Prediction/atoms.h5
    outs:
    - nodes/PredictionMetrics/energy_df.csv
    - nodes/PredictionMetrics/forces_df.csv
    - nodes/PredictionMetrics/plots
    - nodes/PredictionMetrics/stress_df.csv
    metrics:
    - nodes/PredictionMetrics/energy.json:
        cache: false
    - nodes/PredictionMetrics/forces.json:
        cache: false
    - nodes/PredictionMetrics/stress.json:
        cache: false
  model_2:
    cmd: zntrack run ipsuite.models.mace_model.MACE --name model_2
    deps:
    - nodes/train_data/selected_configurations.json
    - nodes/validate_data/selected_configurations.json
    params:
    - model_2
    outs:
    - nodes/model_2/model
    - nodes/model_2/test-data.extxyz
    - nodes/model_2/train-data.extxyz
    plots:
    - nodes/model_2/training.csv:
        template: /data/fzills/tools/ipsuite/ipsuite/static_data/y_log.json
        x: epoch
        y: loss
  model_3:
    cmd: zntrack run ipsuite.models.mace_model.MACE --name model_3
    deps:
    - nodes/train_data/selected_configurations.json
    - nodes/validate_data/selected_configurations.json
    params:
    - model_3
    outs:
    - nodes/model_3/model
    - nodes/model_3/test-data.extxyz
    - nodes/model_3/train-data.extxyz
    plots:
    - nodes/model_3/training.csv:
        template: /data/fzills/tools/ipsuite/ipsuite/static_data/y_log.json
        x: epoch
        y: loss
  model_4:
    cmd: zntrack run ipsuite.models.mace_model.MACE --name model_4
    deps:
    - nodes/train_data/selected_configurations.json
    - nodes/validate_data/selected_configurations.json
    params:
    - model_4
    outs:
    - nodes/model_4/model
    - nodes/model_4/test-data.extxyz
    - nodes/model_4/train-data.extxyz
    plots:
    - nodes/model_4/training.csv:
        template: /data/fzills/tools/ipsuite/ipsuite/static_data/y_log.json
        x: epoch
        y: loss
  model_5:
    cmd: zntrack run ipsuite.models.mace_model.MACE --name model_5
    deps:
    - nodes/train_data/selected_configurations.json
    - nodes/validate_data/selected_configurations.json
    params:
    - model_5
    outs:
    - nodes/model_5/model
    - nodes/model_5/test-data.extxyz
    - nodes/model_5/train-data.extxyz
    plots:
    - nodes/model_5/training.csv:
        template: /data/fzills/tools/ipsuite/ipsuite/static_data/y_log.json
        x: epoch
        y: loss
  ensemble_model:
    cmd: zntrack run ipsuite.models.ensemble.EnsembleModel --name ensemble_model
    deps:
    - nodes/model_1/model
    - nodes/model_1/test-data.extxyz
    - nodes/model_1/train-data.extxyz
    - nodes/model_1/training.csv
    - nodes/model_2/model
    - nodes/model_2/test-data.extxyz
    - nodes/model_2/train-data.extxyz
    - nodes/model_2/training.csv
    - nodes/model_3/model
    - nodes/model_3/test-data.extxyz
    - nodes/model_3/train-data.extxyz
    - nodes/model_3/training.csv
    - nodes/model_4/model
    - nodes/model_4/test-data.extxyz
    - nodes/model_4/train-data.extxyz
    - nodes/model_4/training.csv
    - nodes/model_5/model
    - nodes/model_5/test-data.extxyz
    - nodes/model_5/train-data.extxyz
    - nodes/model_5/training.csv
    outs:
    - nodes/ensemble_model/uuid.json
  ensemble_prediction:
    cmd: zntrack run ipsuite.analysis.model.predict.Prediction --name ensemble_prediction
    deps:
    - nodes/ensemble_model/uuid.json
    - nodes/test_data/selected_configurations.json
    outs:
    - nodes/ensemble_prediction/atoms.h5
  ensemble_analysis:
    cmd: zntrack run ipsuite.analysis.model.predict.PredictionMetrics --name ensemble_analysis
    deps:
    - nodes/ensemble_prediction/atoms.h5
    outs:
    - nodes/ensemble_analysis/energy_df.csv
    - nodes/ensemble_analysis/forces_df.csv
    - nodes/ensemble_analysis/plots
    - nodes/ensemble_analysis/stress_df.csv
    metrics:
    - nodes/ensemble_analysis/energy.json:
        cache: false
    - nodes/ensemble_analysis/forces.json:
        cache: false
    - nodes/ensemble_analysis/stress.json:
        cache: false
