stages:
  AddData:
    cmd: zntrack run ipsuite.data_loading.add_data_ase.AddData --name AddData
    deps:
    - KCl1650K.extxyz
    params:
    - AddData
    outs:
    - nodes/AddData/atoms.h5
  test_data:
    cmd: zntrack run ipsuite.configuration_selection.uniform_energetic.UniformEnergeticSelection
      --name test_data
    deps:
    - nodes/AddData/atoms.h5
    params:
    - test_data
    outs:
    - nodes/test_data/selected_configurations.json
  train_data:
    cmd: zntrack run ipsuite.configuration_selection.random.RandomSelection --name
      train_data
    deps:
    - nodes/AddData/atoms.h5
    - nodes/test_data/selected_configurations.json
    params:
    - train_data
    outs:
    - nodes/train_data/selected_configurations.json
  MLModel:
    cmd: zntrack run ipsuite.models.gap.GAP --name MLModel
    deps:
    - nodes/train_data/selected_configurations.json
    params:
    - MLModel
    outs:
    - nodes/MLModel/gap.input
    - nodes/MLModel/model
    - nodes/MLModel/train_atoms.extxyz
  Prediction:
    cmd: zntrack run ipsuite.analysis.model.predict.Prediction --name Prediction
    deps:
    - nodes/MLModel/gap.input
    - nodes/MLModel/model
    - nodes/MLModel/train_atoms.extxyz
    - nodes/test_data/selected_configurations.json
    outs:
    - nodes/Prediction/atoms.h5
  PredictionMetrics:
    cmd: zntrack run ipsuite.analysis.model.predict.PredictionMetrics --name PredictionMetrics
    deps:
    - nodes/Prediction/atoms.h5
    outs:
    - nodes/PredictionMetrics/energy_df.csv
    - nodes/PredictionMetrics/forces_df.csv
    - nodes/PredictionMetrics/plots
    - nodes/PredictionMetrics/stress_df.csv
    metrics:
    - nodes/PredictionMetrics/energy.json:
        cache: false
    - nodes/PredictionMetrics/forces.json:
        cache: false
    - nodes/PredictionMetrics/stress.json:
        cache: false
