stages:
  AddData:
    cmd: zntrack run ipsuite.data_loading.add_data_ase.AddData --name AddData
    deps:
    - KCl1650K.extxyz
    outs:
    - nodes/AddData/atoms.db
    params:
    - AddData
  AnalysePrediction:
    cmd: zntrack run ipsuite.analysis.model.AnalysePrediction --name AnalysePrediction
    deps:
    - nodes/PredictWithModel/predictions.db
    metrics:
    - nodes/AnalysePrediction/energy.json
    - nodes/AnalysePrediction/forces.json
    - nodes/AnalysePrediction/stress.json
    outs:
    - nodes/AnalysePrediction/energy_df.csv
    - nodes/AnalysePrediction/forces_df.csv
    - nodes/AnalysePrediction/plots
    - nodes/AnalysePrediction/stress_df.csv
  PredictWithModel:
    cmd: zntrack run ipsuite.analysis.model.PredictWithModel --name PredictWithModel
    deps:
    - nodes/model_1/model
    - nodes/model_1/test-data.extxyz
    - nodes/model_1/train-data.extxyz
    - nodes/test_data/selected_configurations.json
    outs:
    - nodes/PredictWithModel/predictions.db
  model_1:
    cmd: zntrack run ipsuite.models.mace_model.MACE --name model_1
    deps:
    - nodes/train_data/selected_configurations.json
    - nodes/validate_data/selected_configurations.json
    meta:
      device: cuda
    outs:
    - nodes/model_1/model
    - nodes/model_1/test-data.extxyz
    - nodes/model_1/train-data.extxyz
    params:
    - model_1
  model_2:
    cmd: zntrack run ipsuite.models.mace_model.MACE --name model_2
    deps:
    - nodes/train_data/selected_configurations.json
    - nodes/validate_data/selected_configurations.json
    meta:
      device: cuda
    outs:
    - nodes/model_2/model
    - nodes/model_2/test-data.extxyz
    - nodes/model_2/train-data.extxyz
    params:
    - model_2
  model_3:
    cmd: zntrack run ipsuite.models.mace_model.MACE --name model_3
    deps:
    - nodes/train_data/selected_configurations.json
    - nodes/validate_data/selected_configurations.json
    meta:
      device: cuda
    outs:
    - nodes/model_3/model
    - nodes/model_3/test-data.extxyz
    - nodes/model_3/train-data.extxyz
    params:
    - model_3
  model_4:
    cmd: zntrack run ipsuite.models.mace_model.MACE --name model_4
    deps:
    - nodes/train_data/selected_configurations.json
    - nodes/validate_data/selected_configurations.json
    meta:
      device: cuda
    outs:
    - nodes/model_4/model
    - nodes/model_4/test-data.extxyz
    - nodes/model_4/train-data.extxyz
    params:
    - model_4
  model_5:
    cmd: zntrack run ipsuite.models.mace_model.MACE --name model_5
    deps:
    - nodes/train_data/selected_configurations.json
    - nodes/validate_data/selected_configurations.json
    meta:
      device: cuda
    outs:
    - nodes/model_5/model
    - nodes/model_5/test-data.extxyz
    - nodes/model_5/train-data.extxyz
    params:
    - model_5
  test_data:
    cmd: zntrack run ipsuite.configuration_selection.uniform_energetic.UniformEnergeticSelection
      --name test_data
    deps:
    - nodes/AddData/atoms.db
    outs:
    - nodes/test_data/selected_configurations.json
    params:
    - test_data
  train_data:
    cmd: zntrack run ipsuite.configuration_selection.random.RandomSelection --name
      train_data
    deps:
    - nodes/AddData/atoms.db
    - nodes/test_data/selected_configurations.json
    outs:
    - nodes/train_data/selected_configurations.json
    params:
    - train_data
  validate_data:
    cmd: zntrack run ipsuite.configuration_selection.random.RandomSelection --name
      validate_data
    deps:
    - nodes/train_data/selected_configurations.json
    outs:
    - nodes/validate_data/selected_configurations.json
    params:
    - validate_data
  ModelEnsembleAnalysis:
    cmd: zntrack run ipsuite.analysis.ensemble.ModelEnsembleAnalysis --name ModelEnsembleAnalysis
    deps:
    - nodes/model_1/model
    - nodes/model_1/test-data.extxyz
    - nodes/model_1/train-data.extxyz
    - nodes/model_2/model
    - nodes/model_2/test-data.extxyz
    - nodes/model_2/train-data.extxyz
    - nodes/model_3/model
    - nodes/model_3/test-data.extxyz
    - nodes/model_3/train-data.extxyz
    - nodes/model_4/model
    - nodes/model_4/test-data.extxyz
    - nodes/model_4/train-data.extxyz
    - nodes/model_5/model
    - nodes/model_5/test-data.extxyz
    - nodes/model_5/train-data.extxyz
    - nodes/test_data/selected_configurations.json
    params:
    - ModelEnsembleAnalysis
    outs:
    - nodes/ModelEnsembleAnalysis/histogram.png
    - nodes/ModelEnsembleAnalysis/normal_plot.png
    - nodes/ModelEnsembleAnalysis/prediction_list.json
    - nodes/ModelEnsembleAnalysis/predictions.json
    - nodes/ModelEnsembleAnalysis/sorted_plot.png
  combined_analyse:
    cmd: zntrack run ipsuite.analysis.model.AnalysePrediction --name combined_analyse
    deps:
    - nodes/ModelEnsembleAnalysis/histogram.png
    - nodes/ModelEnsembleAnalysis/normal_plot.png
    - nodes/ModelEnsembleAnalysis/prediction_list.json
    - nodes/ModelEnsembleAnalysis/predictions.json
    - nodes/ModelEnsembleAnalysis/sorted_plot.png
    outs:
    - nodes/combined_analyse/energy_df.csv
    - nodes/combined_analyse/forces_df.csv
    - nodes/combined_analyse/plots
    - nodes/combined_analyse/stress_df.csv
    metrics:
    - nodes/combined_analyse/energy.json
    - nodes/combined_analyse/forces.json
    - nodes/combined_analyse/stress.json
