AddData:
    add_deps: true
    lines_to_read: null
ModelEnsembleAnalysis:
    bins: 100
model_1:
    amsgrad: true
    batch_size: 10
    ema: true
    ema_decay: 0.99
    hidden_irreps: 16x0e + 16x1o
    max_num_epochs: 50
    num_cutoff_basis: 5
    num_interactions: 2
    num_radial_basis: 8
    r_max: 5.0
    seed: 1
    start_swa: 1200
    swa: true
    use_energy: true
    use_forces: true
    use_stresses: false
model_2:
    amsgrad: true
    batch_size: 10
    ema: true
    ema_decay: 0.99
    hidden_irreps: 16x0e + 16x1o
    max_num_epochs: 50
    num_cutoff_basis: 5
    num_interactions: 2
    num_radial_basis: 8
    r_max: 5.0
    seed: 2
    start_swa: 1200
    swa: true
    use_energy: true
    use_forces: true
    use_stresses: false
model_3:
    amsgrad: true
    batch_size: 10
    ema: true
    ema_decay: 0.99
    hidden_irreps: 16x0e + 16x1o
    max_num_epochs: 50
    num_cutoff_basis: 5
    num_interactions: 2
    num_radial_basis: 8
    r_max: 5.0
    seed: 3
    start_swa: 1200
    swa: true
    use_energy: true
    use_forces: true
    use_stresses: false
model_4:
    amsgrad: true
    batch_size: 10
    ema: true
    ema_decay: 0.99
    hidden_irreps: 16x0e + 16x1o
    max_num_epochs: 50
    num_cutoff_basis: 5
    num_interactions: 2
    num_radial_basis: 8
    r_max: 5.0
    seed: 4
    start_swa: 1200
    swa: true
    use_energy: true
    use_forces: true
    use_stresses: false
model_5:
    amsgrad: true
    batch_size: 10
    ema: true
    ema_decay: 0.99
    hidden_irreps: 16x0e + 16x1o
    max_num_epochs: 50
    num_cutoff_basis: 5
    num_interactions: 2
    num_radial_basis: 8
    r_max: 5.0
    seed: 5
    start_swa: 1200
    swa: true
    use_energy: true
    use_forces: true
    use_stresses: false
test_data:
    n_configurations: 500
train_data:
    n_configurations: 100
    seed: 1234
validate_data:
    n_configurations: 10
    seed: 1234
