AddData:
    lines_to_read: 1000
ConfigurationSelection:
    n_configurations: 10
    seed: 1234
ConfigurationSelection_1:
    correlation_time: 1
    n_configurations: 10
    points_per_cycle: 1
    seed: 1234
ConfigurationSelection_1_kernel:
    soap:
        _type: soap_parameter_dataclass
        value:
            l_max: 7
            n_jobs: -1
            n_max: 7
            periodic: true
            r_cut: 9.0
            rbf: gto
            sigma: 1.0
            weighting: null
