ASEGeoOpt:
    data_id: 0
    init_kwargs: {}
    optimizer: BFGS
    repeat:
    - 1
    - 1
    - 1
    run_kwargs:
        fmax: 0.1
ASEMD:
    data_id: -1
    dump_rate: 1
    init_temperature: null
    init_velocity: null
    repeat:
    - 1
    - 1
    - 1
    sampling_rate: 1
    steps: 250
ASEMD_thermostat:
    friction: 0.01
    temperature: 300
    time_step: 0.5
Packmol:
    box: null
    count:
    - 10
    density: 997
    tolerance: 2.0
SmilesToAtoms:
    cell: null
    optimizer: UFF
    seed: 1234
    smiles: O
